# NAVIGATION TREE
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: getting_started/welcome.md
  - Product Manuals:
    - Overview: manuals/overview.md
    - Digital Combo 8:
      - Overview: manuals/s08dc/overview.md
      - Datasheet: assets/datasheet_s08dc.pdf
  - ShowIO API:
    - Overview: osc_api/overview.md
    - Configuration Commands:
      - Overview: osc_api/configuration_commands/overview.md
      - Reset Device Config: osc_api/configuration_commands/reset_device_config.md
      - Get Node Configuration Info: osc_api/configuration_commands/get_node_configuration_info.md
      - Set Device ID: osc_api/configuration_commands/set_device_id.md
      - Get LAN Configuration: osc_api/configuration_commands/get_lan_configuration.md
      - Set Quick IP Prefix: osc_api/configuration_commands/set_quick_ip_prefix.md
      - Set Quick IP Subnet: osc_api/configuration_commands/set_quick_ip_subnet.md
      - Set Quick IP Gateway: osc_api/configuration_commands/set_quick_ip_gateway.md
      - Set Manual IP Address: osc_api/configuration_commands/set_manual_ip_address.md
      - Set Manual IP Subnet: osc_api/configuration_commands/set_manual_ip_subnet.md
      - Set Manual IP Gateway: osc_api/configuration_commands/set_manual_ip_gateway.md
      - Get OSC Configuration: osc_api/configuration_commands/get_osc_configuration.md
      - Set Response Port: osc_api/configuration_commands/set_response_port.md
      - Set Receive Port: osc_api/configuration_commands/set_receive_port.md
      - Subscribe Me: osc_api/configuration_commands/subscribe_me.md
      - Unsubscribe: osc_api/configuration_commands/unsubscribe.md
      - Add Subscriber: osc_api/configuration_commands/add_subscriber.md
      - Remove Subscriber: osc_api/configuration_commands/remove_subscriber.md
      - Set Digital Input Event Message: osc_api/configuration_commands/set_digital_input_event_message.md
      - Clear Digital Input Event Message: osc_api/configuration_commands/clear_digital_input_event_message.md
      - Get Digital Input Report Message: osc_api/configuration_commands/get_digital_input_report_message.md
    - Discovery Commands:
      - Overview: osc_api/discovery_commands/overview.md
      - Device Discovery: osc_api/discovery_commands/device_discovery.md
    - I/O Commands:
      - Overview: osc_api/io_commands/overview.md
      - Set Digital Output: osc_api/io_commands/set_digital_output.md
      - Get Digital Output: osc_api/io_commands/get_digital_output.md
      - Get Digital Input: osc_api/io_commands/get_digital_input.md
      - Get All Digital Inputs: osc_api/io_commands/get_all_digital_inputs.md
    - Utility Commands:
      - Overview: osc_api/utility_commands/overview.md
      - Ping: osc_api/utility_commands/ping.md
      - Default Handler: osc_api/utility_commands/default_handler.md
# SITE CONFIGURATION
site_name: Show Technologies Docs
site_url: https://docs.show-technologies.com/
copyright: Copyright &copy; 2026 Show Technologies
theme:
  name: material
  font: false
  language: en
  logo: assets/logo_darkmode.png
  favicon: assets/ico_darkmode.ico
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      acccent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - content.tooltips
  icon:
    admonition:
      warning: fontawesome/solid/helmet-safety
      tip: fontawesome/solid/graduation-cap

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md

plugins:
  - search
  - table-reader

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/showtechnologies/
    - icon: fontawesome/solid/home
      link: https://www.show-technologies.com


extra_css:
  - stylesheets/extra.css

validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6

watch:
  - includes