# NAVIGATION TREE
nav:
  - Home: index.md
  - ShowIO API:
    - Configuration Commands:
      - Overview: osc_api/configuration_commands/overview.md
      - Get Device Config: osc_api/configuration_commands/get_device_config.md
      - Set Device Config: osc_api/configuration_commands/set_device_config.md
      - Wipe Device Config: osc_api/configuration_commands/wipe_device_config.md
      - Get Config Section - Device ID: osc_api/configuration_commands/get_config_section_device_id.md
      - Set Config Section - Device ID: osc_api/configuration_commands/set_config_section_device_id.md
      - Get Config Section - Metadata: osc_api/configuration_commands/get_config_section_metadata.md
      - Set Config Section - Metadata: osc_api/configuration_commands/set_config_section_metadata.md
      - Get Config Section - Local IP: osc_api/configuration_commands/get_config_section_local_ip.md
      - Set Config Section - Local IP: osc_api/configuration_commands/set_config_section_local_ip.md
      - Get Config Section - OSC: osc_api/configuration_commands/get_config_section_osc.md
      - Set Config Section - OSC: osc_api/configuration_commands/set_config_section_osc.md
      - Set Response Port: osc_api/configuration_commands/set_response_port.md
      - Subscribe Me: osc_api/configuration_commands/subscribe_me.md
      - Unsubscribe: osc_api/configuration_commands/unsubscribe.md
      - Provision Serial Number: osc_api/configuration_commands/provision_serial_number.md
      - Set Digital Input Event Message: osc_api/configuration_commands/set_digital_input_event_message.md
    - Discovery Commands:
      - Overview: osc_api/discovery_commands/overview.md
      - Device Discovery: osc_api/discovery_commands/device_discovery.md
    - I/O Commands:
      - Overview: osc_api/io_commands/overview.md
      - Set Digital Output: osc_api/io_commands/set_digital_output.md
      - Get Digital Output: osc_api/io_commands/get_digital_output.md
      - Get Digital Input: osc_api/io_commands/get_digital_input.md
      - Get All Digital Inputs: osc_api/io_commands/get_all_digital_inputs.md
    - Utility Commands:
      - Overview: osc_api/utility_commands/overview.md
      - Ping: osc_api/utility_commands/ping.md
      - Default Handler: osc_api/utility_commands/default_handler.md
# SITE CONFIGURATION
site_name: Show Technologies Docs
site_url: https://docs.show-technologies.com/
theme:
  name: material
  font: false
  language: en
  logo: assets/logo_darkmode.png
  favicon: assets/ico_darkmode.ico
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      acccent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - content.tooltips
  icon:
    admonition:
      warning: fontawesome/solid/warning

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/showtechnologies/
    - icon: fontawesome/solid/home
      link: https://www.show-technologies.com


extra_css:
  - stylesheets/extra.css

validation:
  omitted_files: warn
  absolute_links: warn  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: warn
  anchors: warn  # New in MkDocs 1.6

watch:
  - includes